server:
  port: 9098
spring:
  application:
    name: msvc-epmapaapi
eureka:
  instance:
    hostname: msvc-epmapaapi  # El nombre del contenedor o el servicio en Docker Compose
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICEURL}:8761/eureka/  # Usar el nombre del servicio Docker
