spring:
  application:
    name: msvc-epmapaapi
  config:
    import: optional:configserver:http://config-server:8888
  #autoconfigure:
  # exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfigura
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false #esto sirve para evitar el jsonignore
  jpa:
    database: POSTGRESQL
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.batch_size: 1000
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.jdbc.fetch_size: 1000
      open-in-view: false
  servlet:
    multipart:
      max-file-size : 10MB
      max-request-size: 10MB
